FROM openjdk:8-jre-slim
WORKDIR /root/kafka-streams-wordcount
COPY target/kafka-streams-wordcount-1.0-SNAPSHOT-jar-with-dependencies.jar /root/kafka-streams-wordcount

CMD java -jar kafka-streams-wordcount-1.0-SNAPSHOT-jar-with-dependencies.jar