FROM openjdk:8-jre-slim
WORKDIR /root/kafka-streams-sentiment
COPY target/kafka-streams-sentiment-1.0-SNAPSHOT-jar-with-dependencies.jar /root/kafka-streams-sentiment

CMD java -jar kafka-streams-sentiment-1.0-SNAPSHOT-jar-with-dependencies.jar