FROM openjdk:8-jre-slim
WORKDIR /root/kafka-producer-twittertweets
COPY target/kafka-producer-twittertweets-1.0-SNAPSHOT-jar-with-dependencies.jar /root/kafka-producer-twittertweets

CMD java -jar kafka-producer-twittertweets-1.0-SNAPSHOT-jar-with-dependencies.jar